options:
  logging: CLOUD_LOGGING_ONLY
steps:
# Step 1: Build Docker image (inside pubsub folder)
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/publisher-service:$SHORT_SHA',
      '.'
    ]
  dir: 'real-time-data-pipeline/pubsub'

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/publisher-service:$SHORT_SHA']

# Step 3: Terraform init (run in root where main.tf is)
- name: 'hashicorp/terraform:light'
  entrypoint: 'terraform'
  args: ['init']
  dir: 'real-time-data-pipeline'  # root

# Step 4: Terraform apply with image_tag variable
- name: 'hashicorp/terraform:light'
  entrypoint: 'terraform'
  args:
    [
      'apply',
      '-auto-approve',
      '-var=image_tag=$SHORT_SHA'
    ]
  dir: 'real-time-data-pipeline/terraform'  # root

timeout: '1200s'
